# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nAz-tfAO3bsEQXIGyOMHydeXlmCk4CwF
"""

from flask import Flask

app = Flask(__name__)

@app.route("/")
def home():
    return "Привет! ИИ-агент hivio работает!"

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=10000)
